# Spring
spring.application.name=verifidadmin
spring.threads.virtual.enabled=true
server.port=8083
debug=false
#scheema
#spring.jpa.properties.hibernate.default_schema=VERIFID3
spring.jpa.open-in-view=false
# VerifID Admin Security
verifidadmin.security.enabled=true
server.servlet.session.timeout=5000s
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
# VerifID Account
verifidadmin.account.auth-server-url=http://192.168.20.218/SecurityApi3002
verifidadmin.account.central-login-url=
verifidadmin.account.logout-url=https://www.google.com/
verifidadmin.account.cbs-name=LEADS_CBS
verifidadmin.account.spark=1
verifidadmin.account.application-id=15
verifidadmin.account.licence-check-enabled=true
# VerifID EC Verification
verifidadmin.ec-verification.api-url=http://192.168.20.218/verifid-api3-new/api/CustOnBoarding/EcNidVerification
# VerifID Customer Profile
verifidadmin.customer-profile.api-base-url=http://192.168.20.218/verifid-api3-new/
verifidadmin.customer-profile.ml-base-url=http://192.168.20.218/VerifIDML/
verifidadmin.customer-profile.report-base-url=http://192.168.20.218/EkycReportDownload/
verifidadmin.customer-profile.image-process-internal=true
verifidadmin.customer-profile.bank-short-name=UBL
# Logger Socket
microcube.logging.socket.host=localhost
microcube.logging.socket.port=5000
microcube.logging.level=DEBUG
# Microcube Data Loading
microcube.mock.enabled=false
microcube.mock.data=10
spring.jpa.hibernate.ddl-auto=none
# Microcube Publisher
microcube.publisher.agent.enabled=true
microcube.publisher.agent.interval=1000
## Strategy realtime, queue
microcube.publisher.publish.strategy=realtime
microcube.publisher.message.max.attempt=2
#Microcube Publisher
microcube.subscriber.agent.enabled=true
microcube.subscriber.agent.interval=1000
##Strategy realtime, queue
microcube.subscriber.subscribe.strategy=realtime
# Logging
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR
# Persistence Logging
#logging.level.org.hibernate.SQL= DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.jpa.show-sql= true
#spring.jpa.properties.hibernate.format_sql= true
# Kafka Server
spring.kafka.bootstrap-servers=localhost:9092
# Kafka Consumer
spring.kafka.consumer.auto-offset-reset=earliest
# Kafka Producer
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.producer.acks=all
# HikariCP
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPool
# Oracle
spring.datasource.url=jdbc:oracle:thin:@//192.168.20.76:1521/BUPRIM
spring.datasource.username=verifid3
spring.datasource.password=verifid
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#logging.config=classpath:log4j2.xml
#logging.file.name=logs/payment-provider.log