### Initiate Cheque Payment
POST http://localhost:8083/Cheque/Payment/Request
Content-Type: application/json

{
  "id": 1,
  "chequeDate": "2025-08-13",
  "accountNumber": "1000001",
  "chequeNumber": "67890",
  "amount": 100000,
  "batchNumber": 1,
  "tracerNumber": 1,
  "narration": "Cheque receive from BACH",
  "channel": "BACH",
  "state": "HONOURED",
  "remarks": "Cheque Honored"
}

### Initiate Cheque Payment
POST http://localhost:8082/ChequePayment/Initiate/XA
Content-Type: application/json

{
  "id": 1,
  "chequeDate": "2025-08-13",
  "accountNumber": "2000001",
  "chequeNumber": "67890",
  "amount": 100000,
  "narration": "Cheque receive from BACH",
  "channel": "BACH"
}

### Initiate Cheque Payment Async
POST http://localhost:8080/ChequePayment/Initiate/Async
Content-Type: application/json

{
  "id": 1,
  "chequeDate": "2025-08-13",
  "accountNumber": "2000001",
  "chequeNumber": "67890",
  "amount": 100000,
  "narration": "Cheque receive from BACH",
  "channel": "BACH"
}

### Initiate Batch Cheque Payment
POST http://localhost:8080/ChequePayment/Initiate/Batch
Content-Type: application/json

[
  {
    "chequeDate": "2025-08-13",
    "accountNumber": "12345",
    "chequeNumber": "67890",
    "amount": 10000,
    "narration": "Cheque receive from BACH",
    "channel": "BACH"
  },
  {
    "chequeDate": "2025-08-13",
    "accountNumber": "67890",
    "chequeNumber": "67890",
    "amount": 15000,
    "narration": "Cheque receive from BACH",
    "channel": "BACH"
  }
]
